image:
  file: .devcontainer/Dockerfile

tasks:
  - init: "dotnet tool restore && dotnet restore"

vscode:
  extensions:
    - editorconfig.editorconfig
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
